name: CI/CD to Vercel

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - README.md

  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

  deploy:
    name: Deploy to Vercel
    needs: ci # Only run if CI (lint/test/build) passes
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            npx vercel --prod --token=$VERCEL_TOKEN --confirm --yes
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            npx vercel --token=$VERCEL_TOKEN --confirm --yes
          fi
